baseURL = "https://netlify-photo-gallery.netlify.com/"
languageCode = "en-us"
title = "Netlify photo gallery"

[menu]
  [[menu.main]]
    identifier = "top"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "ghent_2022_11"
    name = "Ghent, Nov 2022"
    url = "/ghent_2022_11/"
